In [13]:
import pandas

In [15]:
df1=pandas.read_csv("scmp2010.csv").sort_values(by="dates",ascending=True)
df2=pandas.read_csv("scmp2011.csv").sort_values(by="dates",ascending=True)
df3=pandas.read_csv("scmp2012.csv").sort_values(by="dates",ascending=True)
df4=pandas.read_csv("scmp2013.csv").sort_values(by="dates",ascending=True)
df5=pandas.read_csv("scmp2014.csv").sort_values(by="dates",ascending=True)
df6=pandas.read_csv("scmp2015.csv").sort_values(by="dates",ascending=True)
df7=pandas.read_csv("scmp2016.csv").sort_values(by="dates",ascending=True)
df8=pandas.read_csv("scmp2017.csv").sort_values(by="dates",ascending=True)
df9=pandas.read_csv("scmp2018.csv").sort_values(by="dates",ascending=True)

In [16]:
df=pandas.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9], ignore_index=True)

In [22]:
del df["Unnamed: 0"]

In [23]:
df

,title,byline,dates,datetime
0,Good exposure,Anonymous.,1-Apr-10,2010/4/1
1,SFC bid to recoup all HK$1b from firm's IPO Bi...,"Yiu, Enoch.",1-Apr-10,2010/4/1
2,Sudanese civil war risk has CNPC oilfields ove...,Toh Han Shih.,1-Apr-10,2010/4/1
3,The taxi financing rip-off that is taking us a...,with Jake van der Kamp jake.vanderkamp@scmp.com.,1-Apr-10,2010/4/1
4,Announcements,Anonymous.,1-Apr-10,2010/4/1
5,April Fool!,Anonymous.,1-Apr-10,2010/4/1
6,Banners move by Democrats,"Wong, Albert.",1-Apr-10,2010/4/1
7,31 pupils among 78 held in raids on gang alleg...,"Lo, Clifford.",1-Apr-10,2010/4/1
8,Mixed blessings from Zen's trip to Rome,Anonymous.,1-Apr-10,2010/4/1
9,Events,Anonymous.,1-Apr-10,2010/4/1
10,Henderson blames sales delay on loan curbs,"Cheung, Gary; Wong, Olga.",1-Apr-10,2010/4/1
11,In Brief: [1],Anonymous.,1-Apr-10,2010/4/1
12,In Brief,Anonymous.,1-Apr-10,2010/4/1
13,"Insurers, firms argue over when Sars started","Tsui, Yvonne.",1-Apr-10,2010/4/1
14,Settlement reached in suit over lawyer's death...,"Man, Joyce.",1-Apr-10,2010/4/1
15,Government gets 30 applicants for private hosp...,"Yuk-hang, Ng; Lee, Ella.",1-Apr-10,2010/4/1
16,Kicking it,Anonymous.,1-Apr-10,2010/4/1
17,Japanese modern artists shine,Anonymous.,1-Apr-10,2010/4/1
18,"City could become certification centre, says p...","But, Joshua.",1-Apr-10,2010/4/1
19,"HK sets soccer bar too high, even for FergieSo...",Chan Kin-wa.,1-Apr-10,2010/4/1
20,Rig service fees to stay under pressure: COSL,"Ng, Eric.",1-Apr-10,2010/4/1
21,Fortune Reit wins approval to list in HK,"Sito, Peggy.",1-Apr-10,2010/4/1
22,City,Anonymous.,1-Apr-10,2010/4/1
23,Courts,Anonymous.,1-Apr-10,2010/4/1
24,Courts: [1],Anonymous.,1-Apr-10,2010/4/1
25,Courts: [2],Anonymous.,1-Apr-10,2010/4/1
26,Health,Anonymous.,1-Apr-10,2010/4/1
27,Listings,Anonymous.,1-Apr-10,2010/4/1
28,Regulation,Anonymous.,1-Apr-10,2010/4/1
29,"HKU loses top doctor, fuelling brain drain fear","Lee, Ella.",1-Apr-10,2010/4/1
...,...,...,...,...
263616,NaN,NaN,NaN,NaN
263617,NaN,NaN,NaN,NaN
263618,NaN,NaN,NaN,NaN
263619,NaN,NaN,NaN,NaN
263620,NaN,NaN,NaN,NaN
263621,NaN,NaN,NaN,NaN
263622,NaN,NaN,NaN,NaN
263623,NaN,NaN,NaN,NaN
263624,NaN,NaN,NaN,NaN
263625,NaN,NaN,NaN,NaN
263626,NaN,NaN,NaN,NaN
263627,NaN,NaN,NaN,NaN
263628,NaN,NaN,NaN,NaN
263629,NaN,NaN,NaN,NaN
263630,NaN,NaN,NaN,NaN
263631,NaN,NaN,NaN,NaN
263632,NaN,NaN,NaN,NaN
263633,NaN,NaN,NaN,NaN
263634,NaN,NaN,NaN,NaN
263635,NaN,NaN,NaN,NaN
263636,NaN,NaN,NaN,NaN
263637,NaN,NaN,NaN,NaN
263638,NaN,NaN,NaN,NaN
263639,NaN,NaN,NaN,NaN
263640,NaN,NaN,NaN,NaN
263641,NaN,NaN,NaN,NaN
263642,NaN,NaN,NaN,NaN
263643,NaN,NaN,NaN,NaN
263644,NaN,NaN,NaN,NaN
263645,NaN,NaN,NaN,NaN

In [26]:
df.dropna(subset=['title'], how='all', inplace = True)
df

,title,byline,dates,datetime
0,Good exposure,Anonymous.,1-Apr-10,2010/4/1
1,SFC bid to recoup all HK$1b from firm's IPO Bi...,"Yiu, Enoch.",1-Apr-10,2010/4/1
2,Sudanese civil war risk has CNPC oilfields ove...,Toh Han Shih.,1-Apr-10,2010/4/1
3,The taxi financing rip-off that is taking us a...,with Jake van der Kamp jake.vanderkamp@scmp.com.,1-Apr-10,2010/4/1
4,Announcements,Anonymous.,1-Apr-10,2010/4/1
5,April Fool!,Anonymous.,1-Apr-10,2010/4/1
6,Banners move by Democrats,"Wong, Albert.",1-Apr-10,2010/4/1
7,31 pupils among 78 held in raids on gang alleg...,"Lo, Clifford.",1-Apr-10,2010/4/1
8,Mixed blessings from Zen's trip to Rome,Anonymous.,1-Apr-10,2010/4/1
9,Events,Anonymous.,1-Apr-10,2010/4/1
10,Henderson blames sales delay on loan curbs,"Cheung, Gary; Wong, Olga.",1-Apr-10,2010/4/1
11,In Brief: [1],Anonymous.,1-Apr-10,2010/4/1
12,In Brief,Anonymous.,1-Apr-10,2010/4/1
13,"Insurers, firms argue over when Sars started","Tsui, Yvonne.",1-Apr-10,2010/4/1
14,Settlement reached in suit over lawyer's death...,"Man, Joyce.",1-Apr-10,2010/4/1
15,Government gets 30 applicants for private hosp...,"Yuk-hang, Ng; Lee, Ella.",1-Apr-10,2010/4/1
16,Kicking it,Anonymous.,1-Apr-10,2010/4/1
17,Japanese modern artists shine,Anonymous.,1-Apr-10,2010/4/1
18,"City could become certification centre, says p...","But, Joshua.",1-Apr-10,2010/4/1
19,"HK sets soccer bar too high, even for FergieSo...",Chan Kin-wa.,1-Apr-10,2010/4/1
20,Rig service fees to stay under pressure: COSL,"Ng, Eric.",1-Apr-10,2010/4/1
21,Fortune Reit wins approval to list in HK,"Sito, Peggy.",1-Apr-10,2010/4/1
22,City,Anonymous.,1-Apr-10,2010/4/1
23,Courts,Anonymous.,1-Apr-10,2010/4/1
24,Courts: [1],Anonymous.,1-Apr-10,2010/4/1
25,Courts: [2],Anonymous.,1-Apr-10,2010/4/1
26,Health,Anonymous.,1-Apr-10,2010/4/1
27,Listings,Anonymous.,1-Apr-10,2010/4/1
28,Regulation,Anonymous.,1-Apr-10,2010/4/1
29,"HKU loses top doctor, fuelling brain drain fear","Lee, Ella.",1-Apr-10,2010/4/1
...,...,...,...,...
263078,"Tiffany Chan storms into US Women's Open, qual...",NaN,9-May-18,2018-05-09
263079,China set to strengthen economic ties with Jap...,NaN,9-May-18,2018-05-09
263080,One in the eye for burning China facts,NaN,9-May-18,2018-05-09
263081,Taiwan's MediaTek given permission to resume m...,NaN,9-May-18,2018-05-09
263082,Hong Kong rolling out fast-track immigration s...,NaN,9-May-18,2018-05-09
263083,Road-tripping requisites for the digital age: ...,NaN,9-May-18,2018-05-09
263084,in charm's way: a guide to geomundo's simple p...,NaN,9-May-18,2018-05-09
263085,US-China trade war: talking is the way to a so...,NaN,9-May-18,2018-05-09
263086,Ancient wonders,NaN,9-May-18,2018-05-09
263087,Chinese biotech firm Ascletis first to apply f...,NaN,9-May-18,2018-05-09
263088,Hong Kong Palace Museum hopes to have exhibits...,NaN,9-May-18,2018-05-09
263089,BNP Paribas targets mainland investors with so...,NaN,9-May-18,2018-05-09
263090,Hong Kong should do more to foster development...,NaN,9-May-18,2018-05-09
263091,99 down for American out to eat at world's 100...,NaN,9-May-18,2018-05-09
263092,Hong Kong Business Community Joint Conference ...,NaN,9-May-18,2018-05-09
263093,"In Qingdao, chances of winning the housing 'lo...",NaN,9-May-18,2018-05-09
263094,Malaysia's election on Wednesday could be a ti...,NaN,9-May-18,2018-05-09
263095,Demosisto party candidate Agnes Chow launches ...,NaN,9-May-18,2018-05-09
263096,Tech rebound boosts Hong Kong stocks 1.4pc; Sh...,NaN,9-May-18,2018-05-09
263097,Hong Kong leader Carrie Lam voices support for...,NaN,9-May-18,2018-05-09
263098,Oscar Mok found guilty of murdering Dragonair ...,NaN,9-May-18,2018-05-09
263099,Six in 10 teachers want liberal studies to rem...,NaN,9-May-18,2018-05-09
263100,Hongkongers brush off weakening local dollar t...,NaN,9-May-18,2018-05-09
263101,The Trump effect: China to eclipse US power in...,NaN,9-May-18,2018-05-09
263102,Global investors buy China stocks at fastest p...,NaN,9-May-18,2018-05-09
263103,Hong Kong doctor Wong Cheuk-yi faces disciplin...,NaN,9-May-18,2018-05-09
263104,Human trafficking complainant 'no victim' Davi...,NaN,9-May-18,2018-05-09
263105,Part-time drivers not a factor in Hong Kong bu...,NaN,9-May-18,2018-05-09
263106,Kim Jong-un confirmed as Xi Jinping's 'mystery...,NaN,9-May-18,2018-05-09
263107,Legacy of diplomacy,NaN,9-May-18,2018-05-09